name: gestion_mfb
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  #firebase
  firebase_core: ^3.13.0
  firebase_auth: ^5.6.0
  cloud_firestore: ^5.6.9
  firebase_storage: ^12.4.7
  cloud_functions: ^5.5.0
  #imagen
  image_picker: ^1.0.7

  provider: ^6.1.2

  cupertino_icons: ^1.0.8

  #mapa
  flutter_map: ^7.0.2
  latlong2: ^0.9.0
  geolocator: ^11.0.0
  #grafico de barras
  fl_chart: ^0.66.0
  #Mapa de calor
  flutter_map_heatmap: ^0.0.8
  #PDF
  pdf: ^3.10.8
  printing: ^5.12.0
  #Exportar a Excel
  csv: ^5.0.2
  share_plus: ^7.2.1
  path_provider: ^2.1.3


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/avatar_default.png


